image: node:20-slim

stages: # List of stages for jobs, and their order of execution
  - clone-project

before_script:
  - npm i -g firebase-tools --location=global
  - npm install pnpm --location=global

clone-project-job:
  stage: clone-project
  tags:
    - png-projects

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .next/cache/

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

    - if: $CI_PIPELINE_SOURCE == "schedule"

  script:
    - git clone https://pngwasi@bitbucket.org/pngwasi/portfolio.git portfolio
    - export NEXT_PUBLIC_FIREBASE_CONFIG=$NEXT_PUBLIC_FIREBASE_CONFIG
    - export NEXT_PUBLIC_EMAILJS_USER_ID=$NEXT_PUBLIC_EMAILJS_USER_ID
    - export NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=$NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
    - export NEXT_PUBLIC_EMAILJS_SERVICE_ID=$NEXT_PUBLIC_EMAILJS_SERVICE_ID
    - cd portfolio
    - pnpm install
    - pnpm run build
    - firebase deploy --token "$FIREBASE_TOKEN"
    - ls
