# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node

pipelines:
  # Deployment section
  branches:
    main:
      - step:
          name: Build and Export
          script:
            - npm install && npm run build && npm run export
          artifacts:
            - out/**

      - step:
          name: Deploy to Firebase
          deployment: production
          trigger: "automatic"
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT
