# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  # Deployment section
  branches:
    main:
      - step:
          name: "Install pnpm"
          image: node:14.19
          script:
            - curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=7.0.0-rc.7 sh -

      - step:
          name: "Build and export"
          script:
            - pnpm install
            - pnpm run build
            - pnpm run export

      - step:
          name: "Deployment to Production"
          deployment: production
          trigger: "automatic"
          script:
            - pnpm deploy
