# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node

pipelines:
  # Deployment section
  branches:
    main:
      - step:
          name: Build and Export
          script:
            - export NEXT_PUBLIC_FIRE_APIKEY=$NEXT_PUBLIC_FIRE_APIKEY
            - export NEXT_PUBLIC_FIRE_AUTHDOMAIN=$NEXT_PUBLIC_FIRE_AUTHDOMAIN
            - export NEXT_PUBLIC_FIRE_DATABASEURL=$NEXT_PUBLIC_FIRE_DATABASEURL
            - export NEXT_PUBLIC_FIRE_PROJECTID=$NEXT_PUBLIC_FIRE_PROJECTID
            - export NEXT_PUBLIC_FIRE_STORAGEBUCKET=$NEXT_PUBLIC_FIRE_STORAGEBUCKET
            - export NEXT_PUBLIC_FIRE_MESSAGINGSENDERID=$NEXT_PUBLIC_FIRE_MESSAGINGSENDERID
            - export NEXT_PUBLIC_FIRE_APPID=$NEXT_PUBLIC_FIRE_APPID
            - export NEXT_PUBLIC_FIRE_MEASUREMENTID=$NEXT_PUBLIC_FIRE_MEASUREMENTID
            - export NEXT_PUBLIC_EMAILJS_USER_ID=$NEXT_PUBLIC_EMAILJS_USER_ID
            - export NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=$NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
            - export NEXT_PUBLIC_EMAILJS_SERVICE_ID=$NEXT_PUBLIC_EMAILJS_SERVICE_ID

            - npm install && npm run build && npm run export
          artifacts:
            - out/**

      - step:
          name: Deploy to Firebase
          deployment: production
          trigger: "automatic"
          script:
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT
