# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  default:
    - step:
        name: Build and test
        image: node:14.16.0
        script:
          - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7.0.0-rc.7
          - pnpm install
          - pnpm run build # Replace with your build/test…etc. commands
        caches:
          - pnpm
  # deployment section
  branches:
    main:
      - step:
          name: "Deployment to Production"
          deployment: production
          trigger: "manual"
          script:
            - echo "pnpm install && pnpm deploy"
