# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: "Install pnpm"
        script:
          - npm install -g pnpm@next-7
    - step:
        name: "Install dependencies"
        script:
          - pnpm install
    # deployment section
    - step:
        name: "Deployment to Production"
        deployment: production
        trigger: "manual"
        script:
          - echo "pnpm install && pnpm deploy"
